### ISSUE TITLE
Firefox mobile crashes on simple scene

### ISSUE THREAD

**Issue by NinovanderMark** [Cloud9c/threejs-game#1]
Hey there,

First off, really cool project! I just got started but it seems really straightforward to use. I hope this goes places.

That said, I tried a simple scene but Firefox mobile chokes on it and crashes when I try to open it. I'm not sure why that is, but you can find the scene on this webpage:

https://ninovdmark.neocities.org/Software/project-taro/index.html

**Comment by cloud9c** [comment]
I'll take a look. Seems like the issue may be attributed to the ResizeObserver used in App.

**Comment by cloud9c** [comment]
I'm still investigating -- using the ESM library seems to work, but using the UMD library does not work.

**Comment by cloud9c** [comment]
@NinovanderMark The Firefox mobile issue is fixed on my side. Can you check?

**Comment by NinovanderMark** [comment]
The issue is resolved here as well! Thank you for being on top of this!

As a sidenote, performance isn't great for this scene on my Motorola G7 Power, I'm getting single digit FPS, but that's a separate issue.

Thanks again!
