### ISSUE TITLE
Consider going DOTS-like?

### ISSUE THREAD

**Issue by dustinlacewell** [Cloud9c/threejs-game#2]
Taro is looking really exciting, great job, impressed by all of it.

One thing I was dissapointed to see though, is that taro sort of replicates the traditional "fake-ECS" that Unity popularized where "components" are really more like "behaviours".

Is there any chance of taro instead going the more typical ECS style with data components and functional systems?

Thanks.

**Comment by cloud9c** [comment]
True ECS frameworks, like [ecsy](https://ecsy.io/), was something I definitely looked at while working on Taro. I went for the traditional OOP because it felt like the easier route -- both in implementing and utilizing the library. I'm definitely open to going DOTS-like (maybe another branch?), but that would require a lot more research on my end since Taro doesn't have a lot of contributors.

**Comment by dustinlacewell** [comment]
I also wonder if you maybe consider porting Taro to TypeScript and using things like decorators and reflect-metadata on component classes in order to specify the schematic metadata you need for the editor. 

I would love to see Taro move towards DOTS and towards type-safety. Some TypeScript ECS I think are quite good are Tick-Knock https://github.com/mayakwd/tick-knock and Nopun https://github.com/grebaldi/nopun-ecs. Maybe we could use them as inspiration, add reflect-metadata ontop, and come out with a type-safe DOTS-like threejs ECS that is still editor amenable?

**Comment by cloud9c** [comment]
I think porting Taro to TypeScript would be a separate branch, similar to the DefinitelyTyped repo for threejs. At the moment, I don't plan to port Taro to TypeScript, but I'd be open to others contributing to a TypeScript branch.

**Comment by dustinlacewell** [comment]
Maintaining typings is different than porting the codebase to TypeScript. With typings we'd be constantly trying to keep them in sync with the codebase and that sounds Sisyphean. On the other hand, by porting the codebase to TypeScript, the codebase itself becomes the source of typings. Anyway thanks for being straightforward about it.
