### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by svperfecta** [Cloud9c/threejs-game#4]
**Is your feature request related to a problem? Please describe.**

Just wondering where you have the documentation repository for this project.  It's really quite great, and I thought I might have some additions while I work through it.

**Comment by cloud9c** [comment]
Thanks @svperfecta, the documentation is currently under the gh-pages branch.

**Comment by svperfecta** [comment]
Ahh obviously 🤦‍♂️

Cheers!
